---
# vars file for aws_strapi

project_path: /home/ubuntu/my-strapi-project

db_host: strapi-db.cluster-cgziw8sca1w1.us-east-1.rds.amazonaws.com
db_port: 5432
db_name: postgres
db_user: postgres
db_password: DevOps123strapi
