---
- name: Install required packages
  apt:
    name:
      - curl
      - ca-certificates
      - gnupg
    state: present
    update_cache: yes

- name: Add NodeSource Node.js 20 repo
  shell: curl -fsSL https://deb.nodesource.com/setup_20.x | bash -
  args:
    executable: /bin/bash

- name: Install Node.js 20
  apt:
    name: nodejs
    state: present
    update_cache: yes

- name: Check Node version
  command: node -v
  register: node_version

- name: Print Node version
  debug:
    var: node_version.stdout
