---
- name: Install dependencies
  shell: |
    dnf install -y {{ node_dependencies | join(' ') }}

- name: Remove old NodeJS if present
  dnf:
    name: nodejs
    state: absent
  ignore_errors: yes

- name: Add NodeSource repo
  shell: |
    curl -fsSL https://rpm.nodesource.com/setup_{{ node_version }}.x | bash -

- name: Install NodeJS
  dnf:
    name: nodejs
    state: present
