---
- name: Install dependencies
  dnf:
    name: curl
    state: present

- name: Remove old NodeJS
  dnf:
    name: nodejs
    state: absent
  ignore_errors: yes

- name: Add NodeSource repo
  shell: |
    curl -fsSL https://rpm.nodesource.com/setup_20.x | bash -

- name: Install NodeJS
  dnf:
    name: nodejs
    state: present
